### ISSUE TITLE
Example from README is not working

### ISSUE THREAD

**Issue by rannn505** [albingroen/react-cmdk#5] opened 2022-06-14 01:31 UTC
Im using create react app v5.0.1 with react v17.0.2 and getting 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/11806915/173474254-da2c6262-a97b-49dc-ac83-0510593a8bcc.png">

**Comment by albingroen** [comment] 2022-06-14 04:10
Hi, do you mind posting a reproducible repository or a code sandbox?

**Comment by albingroen** [comment] 2022-06-14 14:19
> @albingroen not sure whats the difference (except sandbox is JS and local is TS) here but I couldn't reproduce it over there https://codesandbox.io/s/angry-gauss-rcz3j8?file=/src/App.js
> 
> Im not sure why I getting this error but maybe a bit of a research on what is the root cause of such an error can help us here

I think it might be a React 18 issue. The sandbox seems to be using v17. Which version are you using?

**Comment by albingroen** [comment] 2022-06-14 16:37
> @albingroen Getting the exact same error here on React 17.0.2. Will try to reproduce in sandbox.

Are you using create-react-app?

**Comment by rannn505** [comment] 2022-06-14 20:11
> Im using create react app v5.0.1 with react v17.0.2 and getting <img alt="image" width="890" src="https://user-images.githubusercontent.com/11806915/173474254-da2c6262-a97b-49dc-ac83-0510593a8bcc.png">
@albingroen just mentioned it in the initial comment.

I assume that the issue comes from parts in the code that are not backward compatible with react 17 ...
let us know if we can help ... and thanks 🙏🏽

**Comment by albingroen** [comment] 2022-06-14 21:17
For some weird reason, it works in codesandbox but not locally. Just tried downloading the zip and running it, but I'm running in to the same issue...

**Comment by rannn505** [comment] 2022-06-16 07:23
@albingroen any progress here? do you need help?

**Comment by albingroen** [comment] 2022-06-17 06:06
> @albingroen Not sure if this will help, but I just copied the package contents over to our repo, fixed the imports and it seems to be running just fine like that. Could this be a build-related issue? That might explain why codesandbox is working fine with the same setup.

Hmm, that sounds really weird...

**Comment by honzasusek** [comment] 2022-06-21 09:00
@albingroen I'm afraid that isn't possible, but I think I could at least share our `tsconfig.json`, `package.json` + a general outline of our setup over PM.

**Comment by albingroen** [comment] 2022-06-21 12:39
@honzasusek Alright, you can DM me [here](https://twitter.com/albingroen)

**Comment by honzasusek** [comment] 2022-06-22 12:17
@albingroen no twitter account, sorry, sent you an email instead 👴

**Comment by dutziworks** [comment] 2022-07-01 13:49
Also, I'm adding these tags so people will find this issue easily: 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Child')
```

**Comment by carbonrider** [comment] 2022-07-28 09:15
Having same issue with React 18 on local machine. It is not working and throwing 

`Uncaught TypeError: Cannot read properties of undefined (reading 'Child')`

**Comment by carbonrider** [comment] 2022-07-28 09:25
It seems there is an ongoing discussion about React 18 and Transition component compatibility. I see react-cmdk using Transition component. Check the details here.

https://github.com/tailwindlabs/headlessui/issues/681

**Comment by albingroen** [comment] 2022-08-25 08:58
I don't have the capacity to solve this, unfortunately, so I will close this for now :/

**Closed by albingroen** 2022-08-25 08:58 UTC

**Comment by tanmayairbase** [comment] 2022-09-02 06:08
facing the same issue as well, also was working on codesandbox
